title: Jiongqiu Ren
description: Physical Oceanographer

url: https://john7ren.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 2

navigation:
  - title: Blog
    url: /index.html
  - title: About Me
    url: /about
  - title: Résumé
    url: /resume
  - title: Research
    url: /research
  - title: Journey
    url: /journey

social:
  github: john7ren
  twitter: Jiong7Ren
  #facebook: brianmaierjr
  email: jiong7.ren@gmail.com
  linkedin: www.linkedin.com/in/jiongqiuren/

google_analytics: "UA-58263416-1"

disqus:
    shortname: john
